### PR TITLE
Minor enhancement

### PR DESCRIPTION
**Pull request by motss**
Cache c$.length, avoid using self, added strip-whitespace

### CODE REVIEW

**Comment by TimvdLippe** [comment]
The `c$.length` is part of the code that is extracted from the Polymer dom-if. As I was thinking of splitting that up in the Polymer core repository, could you create a PR to fix it there first?

`self` is opinionated and would rather not change that to a different opinionated variable name for the sake of changing.

`strip-whitespace` is tricky, I will have to investigate the consequences of this change.

**Comment by motss** [comment]
@TimvdLippe Just to confirm with you. Is this file you copied from https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-if.html?

> strip-whitespace is tricky, I will have to investigate the consequences of this change.

Never heard of that before and it can be found in the doc https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#strip-whitespace.

**Comment by TimvdLippe** [comment]
@motss Yes that is the file.

It has an implication if the HTML is pre-formatted and should be rendered as-is. I will try to investigate if it breaks something.

**Comment by TimvdLippe** [comment]
Waiting for resolution of https://github.com/Polymer/polymer/pull/3600

**Comment by TimvdLippe** [comment]
Closing as `iron-lazy-pages` does not ship `iron-lazy-page` any longer.

**Pull request closed without merging**
