### PR TITLE
Complete br element on README

### PR DESCRIPTION
**Pull request by v1s10n-4**
Hey just for add the missing part of the br in README.md
Hope you found it usefull ^^

### CODE REVIEW

**Review by TimvdLippe — COMMENTED** [review]
Hm, this actually looks good to me: 
image

Was there any visual issue you observed?

**Comment by v1s10n-4** [comment]
Shame on me i didn't figure its a br (empty element) 🤣
But the br tag must be an open tag (<br> without /) unless the document is xhtml type...
But thx for your WC it was usefull to us 👌

**Comment by TimvdLippe** [comment]
Hm I think `<br />` is compatible with both XHTML and HTML. Therefore I am inclined to keep it like it is. Is the non-closing element breaking something for you?

Glad this element is useful for you :smile:

**Comment by TimvdLippe** [comment]
Closing this per above comment. Thanks again for your interest in the project!

**Pull request closed without merging**
